config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'users/confirmations'}

  resources :users do 
    member do
      patch :ban
    end
  end

  resources :students
  resources :classrooms
  resources :teachers
  resources :parents
  resources :castordians
  resources :staffs
  resources :contacts
  resources :addresses
  root 'home#index'
  get 'home/about'
  get 'home/update'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  has_one :staff
  has_one :parent

  enum :address_type, {Home: "Home", Office: "Office",}, default: "Home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/castordian.rb
class Castordian < ApplicationRecord
  belongs_to :staff
  
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :teacher
  has_many :student
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  has_one :staff
  has_one :parent

  enum :contact_type, {Mobile: "Mobile", Home: "Home", Office: "Office"}, default: "Mobile"
end

app/models/parent.rb
class Parent < ApplicationRecord
  belongs_to :user
  belongs_to :contact
  belongs_to :address
  has_many :student
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :user
  belongs_to :contact
  belongs_to :address
  has_one :teacher,dependent: :destroy

  enum :staff_type, {Admin: 0, Teacher: 1, Castordian: 2,}, default: :Teacher
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  belongs_to :parent
  belongs_to :classroom
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :staff
  has_one :classroom
end

app/models/user.rb
class User < ApplicationRecord

  has_many :addresses
  has_many :contacts
  has_one  :staff
  has_one :parent
  has_one :student

  # Include default devise modules. Others available are:
  #  :timeoutable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable ,:lockable,:trackable
    
    
    
  validates :email, presence: true
     
  enum :role, {Student: 0, Staff: 1, Parents: 2}, default: :Student
  after_initialize :set_default_role, :if => :new_record?
    def set_default_role
      self.role ||= :Student
    end

   
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def update
  end
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: %i[ show edit update destroy ]

  # GET /staffs or /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1 or /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs or /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to staff_url(@staff), notice: "Staff was successfully created." }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1 or /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to staff_url(@staff), notice: "Staff was successfully updated." }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1 or /staffs/1.json
  def destroy
    @staff.destroy

    respond_to do |format|
      format.html { redirect_to staffs_url, notice: "Staff was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def staff_params
      params.require(:staff).permit(:user_id, :contact_id, :address_id, :staff_type, :salary, :identity_card_number, :father_name, :place_of_birth, :date_of_hiring, :year_of_service, :meta)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/castordians_helper.rb
module CastordiansHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def ban_status(user)
        if user.access_locked? 
            'Unban'
        else
            'Ban'
        end
    end
end

app/views/staffs/_form.html.erb
<%= form_with(model: staff) do |form| %>
  <% if staff.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
        <% staff.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :contact_id, style: "display: block" %>
    <%= form.text_field :contact_id %>
  </div>

  <div>
    <%= form.label :address_id, style: "display: block" %>
    <%= form.text_field :address_id %>
  </div>

  <div>
    <%= form.label :staff_type, style: "display: block" %>
     <%= form.select :address_type, Staff.staff_types.keys %>
  </div>

  <div>
    <%= form.label :salary, style: "display: block" %>
    <%= form.number_field :salary %>
  </div>

  <div>
    <%= form.label :identity_card_number, style: "display: block" %>
    <%= form.number_field :identity_card_number %>
  </div>

  <div>
    <%= form.label :father_name, style: "display: block" %>
    <%= form.text_field :father_name %>
  </div>

  <div>
    <%= form.label :place_of_birth, style: "display: block" %>
    <%= form.text_field :place_of_birth %>
  </div>

  <div>
    <%= form.label :date_of_hiring, style: "display: block" %>
    <%= form.date_field :date_of_hiring %>
  </div>

  <div>
    <%= form.label :year_of_service, style: "display: block" %>
    <%= form.number_field :year_of_service %>
  </div>

  <div>
    <%= form.label :meta, style: "display: block" %>
    <%= form.text_field :meta %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/staffs/_staff.html.erb
<div id="<%= dom_id staff %>">
  <p>
    <strong>User:</strong>
    <%= staff.user_id %>
  </p>

  <p>
    <strong>Contact:</strong>
    <%= staff.contact_id %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= staff.address_id %>
  </p>

  <p>
    <strong>Staff type:</strong>
    <%= staff.staff_type %>
  </p>

  <p>
    <strong>Salary:</strong>
    <%= staff.salary %>
  </p>

  <p>
    <strong>Identity card number:</strong>
    <%= staff.identity_card_number %>
  </p>

  <p>
    <strong>Father name:</strong>
    <%= staff.father_name %>
  </p>

  <p>
    <strong>Place of birth:</strong>
    <%= staff.place_of_birth %>
  </p>

  <p>
    <strong>Date of hiring:</strong>
    <%= staff.date_of_hiring %>
  </p>

  <p>
    <strong>Year of service:</strong>
    <%= staff.year_of_service %>
  </p>

  <p>
    <strong>Meta:</strong>
    <%= staff.meta %>
  </p>

</div>

app/views/staffs/edit.html.erb
<h1>Editing staff</h1>

<%= render "form", staff: @staff %>

<br>

<div>
  <%= link_to "Show this staff", @staff %> |
  <%= link_to "Back to staffs", staffs_path %>
</div>

app/views/staffs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Staffs</h1>

<div id="staffs">
  <% @staffs.each do |staff| %>
    <%= render staff %>
    <p>
      <%= link_to "Show this staff", staff %>
    </p>
  <% end %>
</div>

<%= link_to "New staff", new_staff_path %>

app/views/staffs/new.html.erb
<h1>New staff</h1>

<%= render "form", staff: @staff %>

<br>

<div>
  <%= link_to "Back to staffs", staffs_path %>
</div>

app/views/staffs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @staff %>

<div>
  <%= link_to "Edit this staff", edit_staff_path(@staff) %> |
  <%= link_to "Back to staffs", staffs_path %>

  <%= button_to "Destroy this staff", @staff, method: :delete %>
</div>