config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'users/confirmations'}

  resources :users do 
    member do
      patch :ban
    end
  end

  resources :students
  resources :classrooms
  resources :teachers
  resources :parents
  resources :castordians
  resources :staffs
  resources :contacts
  resources :addresses
  root 'home#index'
  get 'home/about'
  get 'home/update'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  has_one :staff
  has_one :parent

  enum :address_type, {Home: "Home", Office: "Office",}, default: "Home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/castordian.rb
class Castordian < ApplicationRecord
  belongs_to :staff
  
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :teacher
  has_many :student
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  has_one :staff
  has_one :parent

  enum :contact_type, {Mobile: "Mobile", Home: "Home", Office: "Office"}, default: "Mobile"
end

app/models/parent.rb
class Parent < ApplicationRecord
  belongs_to :user
  belongs_to :contact
  belongs_to :address
  has_many :student
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :user
  belongs_to :contact
  belongs_to :address
  has_one :teacher,dependent: :destroy

  enum :staff_type, {Admin: 0, Teacher: 1, Castordian: 2,}, default: :Teacher
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  belongs_to :parent
  belongs_to :classroom
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :staff
  has_one :classroom
end

app/models/user.rb
class User < ApplicationRecord

  has_many :addresses
  has_many :contacts
  has_one  :staff
  has_one :parent
  has_one :student

  # Include default devise modules. Others available are:
  #  :timeoutable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable ,:lockable,:trackable
    
    
    
  validates :email, presence: true
     
  enum :role, {Student: 0, Staff: 1, Parents: 2}, default: :Student
  after_initialize :set_default_role, :if => :new_record?
    def set_default_role
      self.role ||= :Student
    end

   
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def update
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: %i[ show edit update destroy ]

  # GET /teachers or /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1 or /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers or /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to teacher_url(@teacher), notice: "Teacher was successfully created." }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1 or /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to teacher_url(@teacher), notice: "Teacher was successfully updated." }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1 or /teachers/1.json
  def destroy
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to teachers_url, notice: "Teacher was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def teacher_params
      params.require(:teacher).permit(:staff_id, :duty_time_start, :duty_time_end, :speciality, :education_degree, :expirence_in_years, :hire_by, :meta)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/castordians_helper.rb
module CastordiansHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def ban_status(user)
        if user.access_locked? 
            'Unban'
        else
            'Ban'
        end
    end
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher) do |form| %>
  <% if teacher.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
        <% teacher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :staff_id, style: "display: block" %>
    <%= form.text_field :staff_id %>
  </div>

  <div>
    <%= form.label :duty_time_start, style: "display: block" %>
    <%= form.time_field :duty_time_start %>
  </div>

  <div>
    <%= form.label :duty_time_end, style: "display: block" %>
    <%= form.time_field :duty_time_end %>
  </div>

  <div>
    <%= form.label :speciality, style: "display: block" %>
    <%= form.text_field :speciality %>
  </div>

  <div>
    <%= form.label :education_degree, style: "display: block" %>
    <%= form.text_field :education_degree %>
  </div>

  <div>
    <%= form.label :expirence_in_years, style: "display: block" %>
    <%= form.number_field :expirence_in_years %>
  </div>

  <div>
    <%= form.label :hire_by, style: "display: block" %>
    <%= form.text_field :hire_by %>
  </div>

  <div>
    <%= form.label :meta, style: "display: block" %>
    <%= form.text_field :meta %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/_teacher.html.erb
<div id="<%= dom_id teacher %>">
  <p>
    <strong>Staff:</strong>
    <%= teacher.staff_id %>
  </p>

  <p>
    <strong>Duty time start:</strong>
    <%= teacher.duty_time_start %>
  </p>

  <p>
    <strong>Duty time end:</strong>
    <%= teacher.duty_time_end %>
  </p>

  <p>
    <strong>Speciality:</strong>
    <%= teacher.speciality %>
  </p>

  <p>
    <strong>Education degree:</strong>
    <%= teacher.education_degree %>
  </p>

  <p>
    <strong>Expirence in years:</strong>
    <%= teacher.expirence_in_years %>
  </p>

  <p>
    <strong>Hire by:</strong>
    <%= teacher.hire_by %>
  </p>

  <p>
    <strong>Meta:</strong>
    <%= teacher.meta %>
  </p>

</div>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render "form", teacher: @teacher %>

<br>

<div>
  <%= link_to "Show this teacher", @teacher %> |
  <%= link_to "Back to teachers", teachers_path %>
</div>

app/views/teachers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Teachers</h1>

<div id="teachers">
  <% @teachers.each do |teacher| %>
    <%= render teacher %>
    <p>
      <%= link_to "Show this teacher", teacher %>
    </p>
  <% end %>
</div>

<%= link_to "New teacher", new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render "form", teacher: @teacher %>

<br>

<div>
  <%= link_to "Back to teachers", teachers_path %>
</div>

app/views/teachers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @teacher %>

<div>
  <%= link_to "Edit this teacher", edit_teacher_path(@teacher) %> |
  <%= link_to "Back to teachers", teachers_path %>

  <%= button_to "Destroy this teacher", @teacher, method: :delete %>
</div>