config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'users/confirmations'}

  resources :users do 
    member do
      patch :ban
    end
  end

  resources :students
  resources :classrooms
  resources :teachers
  resources :parents
  resources :castordians
  resources :staffs
  resources :contacts
  resources :addresses
  root 'home#index'
  get 'home/about'
  get 'home/update'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  has_one :staff
  has_one :parent

  enum :address_type, {Home: "Home", Office: "Office",}, default: "Home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/castordian.rb
class Castordian < ApplicationRecord
  belongs_to :staff
  
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :teacher
  has_many :student
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  has_one :staff
  has_one :parent

  enum :contact_type, {Mobile: "Mobile", Home: "Home", Office: "Office"}, default: "Mobile"
end

app/models/parent.rb
class Parent < ApplicationRecord
  belongs_to :user
  belongs_to :contact
  belongs_to :address
  has_many :student
end

app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :user
  belongs_to :contact
  belongs_to :address
  has_one :teacher,dependent: :destroy

  enum :staff_type, {Admin: 0, Teacher: 1, Castordian: 2,}, default: :Teacher
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  belongs_to :parent
  belongs_to :classroom
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :staff
  has_one :classroom
end

app/models/user.rb
class User < ApplicationRecord

  has_many :addresses
  has_many :contacts
  has_one  :staff
  has_one :parent
  has_one :student

  # Include default devise modules. Others available are:
  #  :timeoutable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable ,:lockable,:trackable
    
    
    
  validates :email, presence: true
     
  enum :role, {Student: 0, Staff: 1, Parents: 2}, default: :Student
  after_initialize :set_default_role, :if => :new_record?
    def set_default_role
      self.role ||= :Student
    end

   
end

app/controllers/castordians_controller.rb
class CastordiansController < ApplicationController
  before_action :set_castordian, only: %i[ show edit update destroy ]

  # GET /castordians or /castordians.json
  def index
    @castordians = Castordian.all
  end

  # GET /castordians/1 or /castordians/1.json
  def show
  end

  # GET /castordians/new
  def new
    @castordian = Castordian.new
  end

  # GET /castordians/1/edit
  def edit
  end

  # POST /castordians or /castordians.json
  def create
    @castordian = Castordian.new(castordian_params)

    respond_to do |format|
      if @castordian.save
        format.html { redirect_to castordian_url(@castordian), notice: "Castordian was successfully created." }
        format.json { render :show, status: :created, location: @castordian }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @castordian.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /castordians/1 or /castordians/1.json
  def update
    respond_to do |format|
      if @castordian.update(castordian_params)
        format.html { redirect_to castordian_url(@castordian), notice: "Castordian was successfully updated." }
        format.json { render :show, status: :ok, location: @castordian }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @castordian.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /castordians/1 or /castordians/1.json
  def destroy
    @castordian.destroy

    respond_to do |format|
      format.html { redirect_to castordians_url, notice: "Castordian was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_castordian
      @castordian = Castordian.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def castordian_params
      params.require(:castordian).permit(:staff_id, :role, :duty_time, :meta)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def update
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/castordians_helper.rb
module CastordiansHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def ban_status(user)
        if user.access_locked? 
            'Unban'
        else
            'Ban'
        end
    end
end

app/views/castordians/_castordian.html.erb
<div id="<%= dom_id castordian %>">
  <p>
    <strong>Staff:</strong>
    <%= castordian.staff_id %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= castordian.role %>
  </p>

  <p>
    <strong>Duty time:</strong>
    <%= castordian.duty_time %>
  </p>

  <p>
    <strong>Meta:</strong>
    <%= castordian.meta %>
  </p>

</div>

app/views/castordians/_form.html.erb
<%= form_with(model: castordian) do |form| %>
  <% if castordian.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(castordian.errors.count, "error") %> prohibited this castordian from being saved:</h2>

      <ul>
        <% castordian.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :staff_id, style: "display: block" %>
    <%= form.text_field :staff_id %>
  </div>

  <div>
    <%= form.label :role, style: "display: block" %>
    <%= form.number_field :role %>
  </div>

  <div>
    <%= form.label :duty_time, style: "display: block" %>
    <%= form.time_field :duty_time %>
  </div>

  <div>
    <%= form.label :meta, style: "display: block" %>
    <%= form.text_field :meta %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/castordians/edit.html.erb
<h1>Editing castordian</h1>

<%= render "form", castordian: @castordian %>

<br>

<div>
  <%= link_to "Show this castordian", @castordian %> |
  <%= link_to "Back to castordians", castordians_path %>
</div>

app/views/castordians/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Castordians</h1>

<div id="castordians">
  <% @castordians.each do |castordian| %>
    <%= render castordian %>
    <p>
      <%= link_to "Show this castordian", castordian %>
    </p>
  <% end %>
</div>

<%= link_to "New castordian", new_castordian_path %>

app/views/castordians/new.html.erb
<h1>New castordian</h1>

<%= render "form", castordian: @castordian %>

<br>

<div>
  <%= link_to "Back to castordians", castordians_path %>
</div>

app/views/castordians/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @castordian %>

<div>
  <%= link_to "Edit this castordian", edit_castordian_path(@castordian) %> |
  <%= link_to "Back to castordians", castordians_path %>

  <%= button_to "Destroy this castordian", @castordian, method: :delete %>
</div>